version: "2.3"

services:
  ros_kinetic:
    image: ros_kinetic
    build: ../
    container_name: ros_kinetic
    ports:
      - 6080:80
    environment:
      - PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
    #volumes:
    #  - ~/catkin_ws/src:/root/workspace/src

    runtime: nvidia
    command: sleep infinity



